### ISSUE TITLE
Crear todos los campos para las tareas

### ISSUE THREAD

**Issue by franhida** [27-TRM-02/TFG_Agenda#13]
## Tareas
- [x] #14 
- [x] #15
- [x] #16
- [x] #28 

## Pasos
- [x] Actualizar la rama `dev` en local (`git checkout dev && git pull origin dev`)
- [x] Crear la rama `epic/13` (`git checkout -b epic/13`)
- [x] ***Resolver todas las tareas del listado según sus pasos***
- [x] Subir la rama `epic/13` (`git push origin epic/13`)
- [x] Hacer un pull request de `epic/13` contra `dev`
- [x] En el mensaje del merge, añadir `closes #13`
