### ISSUE TITLE
Crear modelo de Categorías

### ISSUE THREAD

**Issue by 27-TRM-02** [27-TRM-02/TFG_Agenda#23]
## Tareas

- [x] #24
- [x] #26
- [x] #25
- [x] #27

## Pasos

- [x] Actualizar la rama `dev` en local (`git checkout dev && git pull origin dev`)
- [x] Crear la rama `epic/23` (`git checkout -b epic/23`)
- [x] ***Resolver todas las tareas del listado según sus pasos***
- [x] Subir la rama `epic/23`
- [x] Hacer un pull request de `epic/[epic_id]` contra `dev`
- [x] En el mensaje del merge, añadir `Closes #23, resolves #[id_PullRequest]`
