### ISSUE TITLE
Crear Controlador de `Categorías`

### ISSUE THREAD

**Issue by 27-TRM-02** [27-TRM-02/TFG_Agenda#30]
## Rutas
- [x] #31 
- [x] #34
- [x] #32
- [x] #33
- [x] #35

Esta entidad sirve para poder categorizar las `Tareas`

## Pasos

- [x] Actualizar la rama `dev` en local (`git checkout dev && git pull origin dev`)
- [x] Crear la rama `epic/30` (`git checkout -b epic/30`)
- [x] ***Resolver todas las tareas del listado según sus pasos***
- [x] Subir la rama `epic/30`
- [x] Hacer un pull request de `epic/30` contra `dev`
- [x] En el mensaje del merge, añadir `Closes #30`
