### ISSUE TITLE
Crear controlador de autenticación

### ISSUE THREAD

**Issue by 27-TRM-02** [27-TRM-02/TFG_Agenda#40]
## Rutas
- [x] #48 
- [x] #49

Este `controlador` sirve para crear usuarios e iniciar sesión

## Pasos

- [x] Actualizar la rama `dev` en local (`git checkout dev && git pull origin dev`)
- [x] Crear la rama `epic/30` (`git checkout -b epic/40`)
- [x] ***Resolver todas las tareas del listado según sus pasos***
- [x] Subir la rama `epic/40`
- [x] Hacer un pull request de `epic/40` contra `dev`
- [x] En el mensaje del merge, añadir `Closes #40`
