### ISSUE TITLE
Crear `entidad` `Usuario`

### ISSUE THREAD

**Issue by 27-TRM-02** [27-TRM-02/TFG_Agenda#41]
## Campos

- [x] #42
- [x] #43
- [x] #44
- [x] #45

## Lógica

La entidad `Usuario` servirá para poder autenticarse y que las entidades tengan dueño.

## Pasos
- [x] Actualizar la rama `dev` en local (`git checkout dev && git pull origin dev`).
- [x] A partir de la rama `dev`, crear una rama que se llame `epic/41` (`git checkout -b epic/41`).
- [x] **Desarrollar la funcionalidad teniendo en cuenta lo anterior.**
- [x] Hacer un commit de la rama `epic/41` (El mensaje debe contener el texto `Closes #41`)
- [x] Hacer un merge con `dev` (`git checkout dev && git merge epic/41`).
- [x] Subir la rama `dev` (`git push origin dev`)
