### ISSUE TITLE
Configurar la aplicación para usar autenticación JWT

### ISSUE THREAD

**Issue by 27-TRM-02** [27-TRM-02/TFG_Agenda#50]
## Tareas

- [x] #51 
- [x] #52
- [x] #53
- [x] #54
- [x] #56
- [x] #57
- [x] #58

## Pasos

- [x] Actualizar la rama `dev` en local (`git checkout dev && git pull origin dev`)
- [x] Crear la rama `epic/50` (`git checkout -b epic/50`)
- [x] **_Resolver todas las tareas del listado según sus pasos_**
- [x] Subir la rama `epic/50`
- [x] Hacer un pull request de `epic/50` contra `dev`
- [ ] En el mensaje del merge, añadir `Closes #50`
