### ISSUE TITLE
Crear páginas de login y registro

### ISSUE THREAD

**Issue by franhida** [27-TRM-02/TFG_Agenda#78]
## Tareas

- [x] #79 
- [x] #80

## Pasos

- [x] Actualizar la rama `dev` en local (`git checkout dev && git pull origin dev`)
- [x] Crear la rama `epic/78` (`git checkout -b epic/78`)
- [x] ***Resolver todas las tareas del listado según sus pasos***
- [x] Subir la rama `epic/78`
- [x] Hacer un pull request de `epic/78` contra `dev`
- [x] En el mensaje del merge, añadir `Closes #78`
