### ISSUE TITLE
Crear módulo de tareas

### ISSUE THREAD

**Issue by franhida** [27-TRM-02/TFG_Agenda#82]
## Tareas

- [x] #[issue_id]
- [x] #[issue_id]
- [x] #[issue_id]

## Pasos

- [x] Actualizar la rama `dev` en local (`git checkout dev && git pull origin dev`)
- [x] Crear la rama `epic/82` (`git checkout -b epic/82`)
- [x] ***Resolver todas las tareas del listado según sus pasos***
- [x] Subir la rama `epic/82`
- [x] Hacer un pull request de `epic/82` contra `dev`
- [x] En el mensaje del merge, añadir `Closes #82`
