### ISSUE TITLE
Crear módulo de categorías

### ISSUE THREAD

**Issue by franhida** [27-TRM-02/TFG_Agenda#83]
## Tareas

- [x] #[issue_id]
- [x] #[issue_id]
- [x] #[issue_id]

## Pasos

- [x] Actualizar la rama `dev` en local (`git checkout dev && git pull origin dev`)
- [x] Crear la rama `epic/83` (`git checkout -b epic/83`)
- [x] ***Resolver todas las tareas del listado según sus pasos***
- [x] Subir la rama `epic/83`
- [x] Hacer un pull request de `epic/83` contra `dev`
- [ ] En el mensaje del merge, añadir `Closes #83`
