### ISSUE TITLE
Crear Crud de Tareas

### ISSUE THREAD

**Issue by franhida** [27-TRM-02/TFG_Agenda#9]
El CRUD se refiere a las operaciones básicas que puede tener un registro, siendo estas:
## Tareas
- [x] Listado 
- [x] Creación
- [x] #10 
- [x] #11 
- [x] #12 

## Pasos
- [x] Actualizar la rama `dev` en local (`git checkout dev && git pull origin dev`)
- [x] Crear la rama `epic/9` (`git checkout -b epic/9`)
- [x] ***Resolver todas las tareas del listado según sus pasos***
- [x] Subir la rama `epic/9`
- [x] Hacer un pull request de `epic/9` contra `dev`
- [x] En el mensaje del merge, añadir `closes #9`
