### ISSUE TITLE
Terminar back-end

### ISSUE THREAD

**Issue by 27-TRM-02** [27-TRM-02/TFG_Agenda#91]
Revisar y comentar todas las funcionalidades del backend

## Tareas

- [x] #96 

## Pasos

- [x] Actualizar la rama `dev` en local (`git checkout dev && git pull origin dev`)
- [x] Crear la rama `back/finish` (`git checkout -b back/finish`)
- [x] ***Resolver todas las tareas del listado según sus pasos***
- [x] Subir la rama `back/finish`
- [x] Hacer un pull request de `back/finish` contra `dev`
- [x] En el mensaje del merge, añadir `Closes #91`
