### ISSUE TITLE
Componentes de categorias

### ISSUE THREAD

**Issue by 27-TRM-02** [27-TRM-02/TFG_Agenda#93]
Crear todos los componentes relacionados con los servicios del módulo categorias

## Tareas

- [x] #95 

## Pasos

- [x] Actualizar la rama `dev` en local (`git checkout dev && git pull origin dev`)
- [x] Crear la rama `tareas` (`git checkout -b categorias`)
- [x] ***Resolver todas las tareas del listado según sus pasos***
- [x] Subir la rama `categorias`
- [x] Hacer un pull request de `categorias` contra `dev`
- [x] En el mensaje del merge, añadir `Closes #93`
